services:
  presto:
    ports:
      - 38080:8080
    volumes:
    #   字体文件保存在 presto-data/fonts 目录下
      - presto-data:/home/presto/.presto
    image: ghcr.io/presto-io/presto
    restart: unless-stopped

volumes:
    presto-data:
        name: presto-data
