services:
  presto:
    image: ghcr.io/presto-io/presto
    ports:
      - 127.0.0.1:8080:8080
    environment:
      PRESTO_INJECT_API_KEY: "true"
      PRESTO_CONFIG_DIR: /config
      PRESTO_DATA_DIR: /data
      PRESTO_CACHE_DIR: /cache
      PRESTO_LOG_DIR: /logs
      FONT_PATHS: /data/fonts:/usr/share/fonts
    volumes:
      - ./.presto-data/config:/config
      - ./.presto-data/data:/data
      - ./.presto-data/cache:/cache
      - ./.presto-data/logs:/logs
    restart: unless-stopped
