package appdata

import (
	"encoding/json"
	"os"
	"path/filepath"
)

const (
	AppName = "Presto"
	AppID   = "com.mrered.presto"

	markerFile = ".presto-generated.json"
	readmeFile = ".presto-cleanup.txt"
)

type Marker struct {
	SchemaVersion   int      `json:"schemaVersion"`
	AppName         string   `json:"appName"`
	AppID           string   `json:"appId"`
	BundleID        string   `json:"bundleId"`
	GeneratedBy     string   `json:"generatedBy"`
	DataDir         string   `json:"dataDir"`
	Purpose         string   `json:"purpose"`
	Removable       bool     `json:"removable"`
	SafeToDelete    string   `json:"safeToDelete"`
	ManagedSubpaths []string `json:"managedSubpaths"`
}

func MarkGenerated(dir string) error {
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}

	absDir, err := filepath.Abs(dir)
	if err != nil {
		absDir = dir
	}

	marker := Marker{
		SchemaVersion: 1,
		AppName:       AppName,
		AppID:         AppID,
		BundleID:      AppID,
		GeneratedBy:   AppName,
		DataDir:       absDir,
		Purpose:       "Downloaded templates, fonts, and other Presto runtime data.",
		Removable:     true,
		SafeToDelete:  "Safe to delete after uninstalling Presto, or when you want to remove downloaded templates and fonts. User documents are not stored here unless you manually put them in this directory.",
		ManagedSubpaths: []string{
			"templates",
			"fonts",
		},
	}

	markerPath := filepath.Join(dir, markerFile)
	data, err := json.MarshalIndent(marker, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	if err := writeFileIfChanged(markerPath, data, 0600); err != nil {
		return err
	}

	readmePath := filepath.Join(dir, readmeFile)
	if err := writeFileIfChanged(readmePath, []byte(cleanupReadme(absDir)), 0600); err != nil {
		return err
	}

	paths := []string{dir, markerPath, readmePath}
	for _, subpath := range marker.ManagedSubpaths {
		path := filepath.Join(dir, subpath)
		if _, err := os.Stat(path); err == nil {
			paths = append(paths, path)
		}
	}
	markPlatformGenerated(paths, marker)

	return nil
}

func cleanupReadme(absDir string) string {
	return "This directory was generated by Presto (" + AppID + ").\n" +
		"Path: " + absDir + "\n\n" +
		"It stores downloaded templates, fonts, and other runtime data.\n" +
		"It is safe to delete after uninstalling Presto, or when you want to remove downloaded templates and fonts.\n" +
		"Deleting it does not remove your documents unless you manually saved documents inside this directory.\n"
}

func writeFileIfChanged(path string, data []byte, perm os.FileMode) error {
	if current, err := os.ReadFile(path); err == nil && string(current) == string(data) {
		return nil
	}
	return os.WriteFile(path, data, perm)
}
